name: Deploy to EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Assemble the project
      run: ./gradlew assemble

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build Docker image
      run: docker build -t myapp .

    - name: Tag Docker image
      run: docker tag myapp ${{ secrets.DOCKERHUB_USERNAME }}/project-backend

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/project-backend

    - name: SSH into EC2 instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/project-backend
          docker stop myapp-container || true
          docker rm myapp-container || true
          docker run -d --name project-backend -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/project-backend
